package prototype.helpers

import kotlinx.serialization.Serializable

sealed class LLMResponse

/**
 * Contains the complete response data returned by the Ollama service.
 *
 * @property model The identifier of the model that generated the response
 * @property created_at ISO 8601 timestamp when the response was generated
 * @property response The actual text generated by the language model
 * @property done Boolean indicating if the generation is complete
 * @property done_reason Reason code for completion (e.g., "stop", "length", "error")
 */
@Serializable
data class OllamaResponse(
    val model: String,
    val created_at: String,
    val response: String?,
    val done: Boolean,
    val done_reason: String,
) : LLMResponse()

@Serializable
data class OpenAIResponse(
    val response: String,
) : LLMResponse()
