name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
      with:
        version: 2.1.0

    - name: Install dependencies
      working-directory: one-day-poc-server
      run: npm ci
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run backend tests
      working-directory: one-day-poc-server
      run: |
        chmod +x gradlew
        ./gradlew test clean
