name: Frontend Tests

on:
  push:
    branches: [ "main", "staging", "production" ]
  pull_request:
    branches: [ "main", "staging", "production" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: one-day-poc-client/package-lock.json

    - name: Install dependencies
      working-directory: one-day-poc-client
      run: npm ci

    - name: Run tests
      working-directory: one-day-poc-client
      run: npm test -- --watch=false --passWithNoTests
